collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7170213
  brandStrength: 0.9319149
  lightness: 0.5085106
  brandColors:
    - '#3D69CA'
    - '#000000'
    - '#DFECFE'
    - '#738433'
    - '#AAA56E'
  rhythmicContrast: 1
typography_spectrum: 0.6635751
layout_spectrum: 0.4814503
name: ajohnsonphotography
