collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5104565529618412
  brandStrength: 1
  lightness: 0.1584882235620171
  brandColors:
    - '#3D69CA'
    - '#000000'
    - '#DFECFE'
    - '#738433'
    - '#AAA56E'
  rhythmicContrast: 0.4980456121265888
typography_spectrum: 0.6635751
layout_spectrum: 1
name: ajohnsonphotography
